In [6]:
import yaml
import numpy as np
import matplotlib.pyplot as plt

def load_yaml(path: str) -> dict:
    """Load yaml file to dict"""
    with open(path, "r") as file:
        yaml_dct = yaml.safe_load(file)
    return yaml_dct

def unique_msgs_of_length_n(n):
    def all_bits(m):
        if m: yield from (bits + bit for bits in all_bits(m-1) for bit in ("0", "1"))
        else: yield ""

    bits_combs = []
    for bits in all_bits(n):
        bits_combs.append([int(b) for b in bits])
    return np.array(bits_combs)

def get_msg_accs_for_unique_msgs(enc_msgs, dec_msgs):
    msg_length = enc_msgs.shape[1]
    unique_msgs = unique_msgs_of_length_n(msg_length)
    unique_msgs_accs = []
    for i in range(len(unique_msgs)):
        mask = enc_msgs == unique_msgs[i]
        acc = (enc_msgs[mask] == dec_msgs[mask]).mean()
        unique_msgs_accs.append(acc)

    unique_msgs_accs = np.array(unique_msgs_accs)
    return unique_msgs_accs

In [18]:
def summary(filename):
    results = load_yaml(filename)
    result = results['ApproxJPEG_Q(70)_std(0.01)__Identity']

    dec_msgs = np.array([r['dec_message'] for r in result])
    enc_msgs = np.array([r['message'] for r in result])
    ious = np.array([r['iou'] for r in result])
    print("IoU: ", ious.mean().round(2))
    print("Acc: ", (dec_msgs == enc_msgs).mean().round(2))
    print("Per-bit Acc: ", (dec_msgs == enc_msgs).mean(axis=0).round(2).tolist())
    print("Zeros Acc: ", (enc_msgs[enc_msgs == 0] == dec_msgs[enc_msgs == 0]).mean().round(2))
    print("Ones Acc: ", (enc_msgs[enc_msgs == 1] == dec_msgs[enc_msgs == 1]).mean().round(2))


    print("Per-msg Acc: ", )
    unique_msgs = unique_msgs_of_length_n(6)
    unique_msgs_accs = get_msg_accs_for_unique_msgs(enc_msgs, dec_msgs)
    idxs = unique_msgs_accs.argsort()

    for msg, acc in zip(unique_msgs[idxs], unique_msgs_accs[idxs]):
        print(msg, f"{acc:.2f}")

In [19]:
summary("results.yaml")

IoU:  0.95
Acc:  0.91
Per-bit Acc:  [0.98, 0.97, 0.71, 0.85, 0.98, 0.97]
Zeros Acc:  0.88
Ones Acc:  0.94
Per-msg Acc: 
[1 0 0 1 1 0] 0.83
[1 0 0 1 0 0] 0.83
[0 0 0 1 1 0] 0.83
[0 0 0 1 0 0] 0.83
[1 1 0 1 1 0] 0.83
[1 0 0 1 1 1] 0.83
[1 1 0 1 0 0] 0.83
[1 0 0 1 0 1] 0.83
[0 1 0 1 1 0] 0.84
[0 0 0 1 1 1] 0.84
[0 1 0 1 0 0] 0.84
[0 0 0 1 0 1] 0.84
[1 1 0 1 1 1] 0.84
[1 1 0 1 0 1] 0.84
[0 1 0 1 1 1] 0.84
[0 1 0 1 0 1] 0.84
[1 0 0 0 1 0] 0.88
[1 0 0 0 0 0] 0.88
[0 0 0 0 1 0] 0.88
[0 0 0 0 0 0] 0.88
[1 1 0 0 1 0] 0.88
[1 0 0 0 1 1] 0.88
[1 1 0 0 0 0] 0.88
[1 0 0 0 0 1] 0.88
[0 1 0 0 1 0] 0.89
[0 0 0 0 1 1] 0.89
[0 1 0 0 0 0] 0.89
[0 0 0 0 0 1] 0.89
[1 1 0 0 1 1] 0.89
[1 1 0 0 0 1] 0.89
[0 1 0 0 1 1] 0.89
[0 1 0 0 0 1] 0.89
[1 0 1 1 1 0] 0.92
[1 0 1 1 0 0] 0.92
[0 0 1 1 1 0] 0.93
[0 0 1 1 0 0] 0.93
[1 1 1 1 1 0] 0.93
[1 0 1 1 1 1] 0.93
[1 1 1 1 0 0] 0.93
[1 0 1 1 0 1] 0.93
[0 1 1 1 1 0] 0.93
[0 0 1 1 1 1] 0.93
[0 1 1 1 0 0] 0.93
[0 0 1 1 0 1] 0.93
[1 1 1 1 1 1] 0.94
[1 1 1 1 0 1] 0.94
[0 1 1

In [20]:
summary("results_2.yaml")

IoU:  0.97
Acc:  0.9
Per-bit Acc:  [0.91, 0.86, 0.92, 0.87, 0.92, 0.91]
Zeros Acc:  0.89
Ones Acc:  0.9
Per-msg Acc: 
[1 0 0 1 1 0] 0.83
[1 0 0 0 1 0] 0.84
[1 0 0 1 1 1] 0.84
[1 0 1 1 1 0] 0.84
[1 0 0 1 0 0] 0.85
[0 0 0 1 1 0] 0.86
[1 0 0 0 1 1] 0.86
[1 0 1 0 1 0] 0.86
[1 0 0 0 0 0] 0.86
[1 0 1 1 1 1] 0.86
[1 0 0 1 0 1] 0.86
[1 0 1 1 0 0] 0.86
[0 0 0 0 1 0] 0.87
[0 0 0 1 1 1] 0.87
[0 0 1 1 1 0] 0.87
[1 1 0 1 1 0] 0.87
[1 0 1 0 1 1] 0.87
[0 0 0 1 0 0] 0.87
[1 0 0 0 0 1] 0.88
[1 0 1 0 0 0] 0.88
[1 0 1 1 0 1] 0.88
[0 0 0 0 1 1] 0.89
[0 0 1 0 1 0] 0.89
[1 1 0 0 1 0] 0.89
[0 0 1 1 1 1] 0.89
[1 1 0 1 1 1] 0.89
[0 0 0 0 0 0] 0.89
[1 1 1 1 1 0] 0.89
[0 0 0 1 0 1] 0.89
[0 0 1 1 0 0] 0.89
[1 1 0 1 0 0] 0.89
[1 0 1 0 0 1] 0.89
[0 1 0 1 1 0] 0.90
[0 0 1 0 1 1] 0.90
[1 1 0 0 1 1] 0.90
[1 1 1 0 1 0] 0.90
[1 1 1 1 1 1] 0.90
[0 0 0 0 0 1] 0.90
[0 0 1 0 0 0] 0.90
[1 1 0 0 0 0] 0.91
[0 0 1 1 0 1] 0.91
[1 1 0 1 0 1] 0.91
[1 1 1 1 0 0] 0.91
[0 1 0 0 1 0] 0.92
[0 1 0 1 1 1] 0.92
[0 1 1 1 1 0] 0.92
[1 1 1 0